### ISSUE TITLE
Feature: ability to specify an optional call limit at the account and service provider level

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-webapp#109]
There is a new feature we have added to the API that allows the system to limit the number of concurrent calls allowed for a given account and/or service provider.  To support this, there are two new tables:

```
CREATE TABLE service_provider_limits
(
service_provider_limits_sid CHAR(36) NOT NULL UNIQUE ,
service_provider_sid CHAR(36) NOT NULL,
category ENUM('api_rate','voice_call_session', 'device') NOT NULL,
quantity INTEGER NOT NULL,
PRIMARY KEY (service_provider_limits_sid)
);
CREATE TABLE account_limits
(
account_limits_sid CHAR(36) NOT NULL UNIQUE ,
account_sid CHAR(36) NOT NULL,
category ENUM('api_rate','voice_call_session', 'device') NOT NULL,
quantity INTEGER NOT NULL,
PRIMARY KEY (account_limits_sid)
);
```
> Note: although we allow for limiting number of api calls/min and number of devices registered, this is not currently implemented in the API - only the limit of number of calls (voice_call_session) is implemented for now.

There is new associated APIs:
```
POST /ServiceProviders/:sid/Limits
{category: 'voice_call_session', quantity: 100}

GET /ServiceProviders/:sid/Limits

and similarly

POST /Accounts/:sid/Limits
{category: 'voice_call_session', quantity: 100}

GET /Accounts/:sid/Limits
```
swagger doc [here](https://github.com/jambonz/jambonz-api-server/blob/052a19cfdc36acb50d890d6b1d9e69b786f7212a/lib/swagger/swagger.yaml#L1858) and [here](https://github.com/jambonz/jambonz-api-server/blob/052a19cfdc36acb50d890d6b1d9e69b786f7212a/lib/swagger/swagger.yaml#L1916).

> Note: the POST will update an existing limit if one exists, otherwise create one.

What is needed now is the ability to view and set the limits in the jambonz webapp.  We need this in both the "legacy" webapp (main branch) as well as the "refresh" branch, but the priority is the main branch.

On the Settings page (which is about the service provider) we should add:
- an input field labeled "Max Concurrent Calls"

Similarly on the Accounts page
- an input field labeled "Max Concurrent Calls"

The value of the field shall be populated using the GET apis above.  If the user enters a value, then we should populate to the database using the POST API above.

Note: a value of 0 is taken to mean no limit will be applied.

**Comment by davehorton** [comment]
The APIs are fully implemented on the main branch of jambonz-api-server so `npm run integration-test` should give what you need.  If an additional API is needed (for instance, a delete?) just let me know

**Comment by kitajchuk** [comment]
@davehorton I checked out the Swagger docs running the latest from `main` locally for the API server and it looks like they don't clearly articulate the need to send/receive the `quantity` field. My understanding is we would be posting and fetching a small JSON payload that actually has the schema `{ category: string; quantity: number; }` correct?

<img width="542" alt="Screen Shot 2022-09-20 at 7 27 36 AM" src="https://user-images.githubusercontent.com/438711/191285340-73a14aea-f659-48a5-ac73-79f4a9e16cff.png">

<img width="543" alt="Screen Shot 2022-09-20 at 7 27 46 AM" src="https://user-images.githubusercontent.com/438711/191285344-a6d02d70-a110-4b9a-88ca-fbf311d3cd72.png">

**Comment by kitajchuk** [comment]
@davehorton I'm a little confused about the data model here. These APIs return arrays for the :GET request so is the long term realization that there would be a limit for each of the categories but for the moment we are only supporting the voice_call_session category?

**Comment by davehorton** [comment]
you are right.....I will fix the swagger.  The api itself should work though as you described

**Comment by davehorton** [comment]
yes, on the hosted platform we do limit on all 3 factors actually.  On the open source, right now we only have a requirement to limit on concurrent calls, and that is all I want to implement at the moment.

**Comment by kitajchuk** [comment]
> yes, on the hosted platform we do limit on all 3 factors actually. On the open source, right now we only have a requirement to limit on concurrent calls, and that is all I want to implement at the moment.

For future thinking of the app implementation, what would the labels be for `api_rate` and `device` given that `voice_call_session` uses the label "Max Concurrent Calls"?

**Comment by davehorton** [comment]
api_rate = "Max api calls per minute"
device = "Max registered devices"

**Comment by kitajchuk** [comment]
> api_rate = "Max api calls per minute"
> device = "Max registered devices"

Cool. I played quickly on local dev to see and it looks like the api also returns a service provider sid or account sid respectively as well for a limit. I have a plan for how to implement this on the new app. As for the immediate need with the current app I may have time later unless @khanghugo or @xquanluu want to take a stab at that? It should be easy:

For settings add the limits fetch in the useEffect and create a state var for the max concurrent calls. Add an input for it, ideally of type number with min set to 0. On submit just make the extra post request to the limit api for this one category. Since only the one category is in scope use array find method yo only work with the one limit.

For accounts it’s basically the same but you would need to either 1) only add the field if the type is edit or 2) add the field either way just know you cannot make the 1st post to save the limit until after the create post of the new account since you won’t have the account sid until then.

Option 2 would work for both add/edit but technically there’s no reason to bottleneck the limit post behind the put when updating an existing account 🤔. However this would be the case in this approach.

Anyone ping here if you want to tackle this otherwise I’ll assume to take a poke at it later if there’s no traction 😅.

**Comment by khanghugo** [comment]
Sorry. I don't think I can make time for this as of now. @xquanluu feel free to chip in.

**Comment by kitajchuk** [comment]
@davehorton There seems to be a bug in the backend API. I have two accounts locally and I created limits for my initial default account. However, my other account is returning the limits set for the default account even though this account actually has no limits set. It looks like there is missing some account_sid filtering on the backend 🤔?

<img width="1509" alt="Screen Shot 2022-09-20 at 1 27 45 PM" src="https://user-images.githubusercontent.com/438711/191358518-40cedba4-de18-4bd4-b226-e16c2ff9f582.png">

**Comment by davehorton** [comment]
er...will check

**Comment by kitajchuk** [comment]
> yes, you are right. Working on a fix now

Cool cool.

**Comment by davehorton** [comment]
ok I pushed a fix

**Comment by xquanluu** [comment]
Start working on this.

**Comment by kitajchuk** [comment]
> ok I pushed a fix

Okay, that works now 👍 . I have this covered for the `refresh` branch.

**Comment by davehorton** [comment]
It would be preferable that if there is no limit to start with (the field will appear blank) that we dont then post, because the sudden appearance of a zero in the field might confuse the user.

**Comment by kitajchuk** [comment]
> It would be preferable that if there is no limit to start with (the field will appear blank) that we dont then post, because the sudden appearance of a zero in the field might confuse the user.

Ok cool. I’ll make that change 🤘

**Comment by kitajchuk** [comment]
@davehorton Made that change so it looks like this now if nothing is entered and we don't post unless the user enters a value:

<img width="584" alt="Screen Shot 2022-09-21 at 6 19 05 AM" src="https://user-images.githubusercontent.com/438711/191515124-3808204f-ffcd-48d8-8d8e-3fd83ac52c29.png">

**Comment by davehorton** [comment]
Nice!

**Comment by kitajchuk** [comment]
> Nice!

Here's what it would look like with all three enabled. This is set up so all we have to do is uncomment some lines of code in a constant to enable more limit categories.

<img width="591" alt="Screen Shot 2022-09-21 at 9 23 56 AM" src="https://user-images.githubusercontent.com/438711/191559080-e9343c2f-2f55-4b6d-bf56-363003a6e91e.png">

<img width="499" alt="Screen Shot 2022-09-21 at 9 24 54 AM" src="https://user-images.githubusercontent.com/438711/191559084-ceefc22b-4eaf-4ca9-8ec3-94d3632e702b.png">

**Comment by kitajchuk** [comment]
@davehorton If I delete a ServiceProvider or an Account does the backend do the cleanup work to delete these limit entities as well? If not then it should. Otherwise we'd need a DELETE API, however I feel like it's cleaner for the backend to handle it...

Another question has to do with the idea of a user "soft" deleting a limit. Once a user enters a quantity and saves it they could presumably delete the value in that field and save again. E.g. a "soft" delete. Currently idk if this is handled properly in either the PR for the main branch or my refresh implementation. Since the API expects a number for quantity we use `Number(e.target.value)` which seemed to get carried over to the main branch PR. However, I neglected to consider that `Number("") === 0` so on the refresh branch when you "delete" the input field value it essentially coerces to 0. Presumably this is fine since 0 means unlimited which I presume is the same as not having a limit saved at all. The thing on the main branch PR is the value check is loose so the 0 is falsey and an empty string is rendered instead, even though actually a limit is set with a quantity of 0 and we can see this technically exists in the API. Also on the main branch because of this loose check I actually can't even type a 0 into the field lol. Trying to do that renders an empty value which also feels very weird.

**Comment by davehorton** [comment]
These two tables have an ON CASCADE DELETE foreign key so if a SP or account is deleted the associated rows will be automatically cleared (and the delete operation will not be blocked)

**Comment by davehorton** [comment]
I agree a delete API is needed, and that once we have that it would be nice to let the user clear an existing limit, have an empty field, click save and have the limit removed in the db -- and the blank field stays blank, not automagically populated with a zero.  I will add the api

**Comment by davehorton** [comment]
Actually, there is a delete API, I just forgot to put it into the swagger doc (will do that shortly).

```
DELETE /ServiceProviders/:sid/Limits                                                    # deletes all limits for an SP
DELETE /ServiceProviders/:sid/Limits?category=voice_call_session  # deletes a specific type of limit for an SP

DELETE /Accounts/:sid/Limits                                                    # deletes all limits for an account
DELETE /Accounts/:sid/Limits?category=voice_call_session  # deletes a specific type of limit for an account

```

**Comment by kitajchuk** [comment]
> Actually, there is a delete API, I just forgot to put it into the swagger doc (will do that shortly).
> 
> ```
> DELETE /ServiceProviders/:sid/Limits    # deletes all limits for an SP
> DELETE /ServiceProviders/:sid/Limits?category=voice_call_session  # deletes a specific type of limit for an SP
> 
> DELETE /Accounts/:sid/Limits     # deletes all limits for an account
> DELETE /Accounts/:sid/Limits?category=voice_call_session  # deletes a specific type of limit for an account
> ```

Nice. 👍

**Comment by kitajchuk** [comment]
@davehorton Okay this is functioning as expected now on the refresh branch with the latest commit here: https://github.com/jambonz/jambonz-webapp/pull/64/commits/e64260bf890c1724fc1758bf970c0cddc3a3a004.

- Only numbers greater than or equal to 0 can be entered
- The field can be emptied to contain no value (signals for :DELETE)
- On save limits are either updated (if a value exists) or deleted (if no value exists e.g. empty)
- Deleted limits are gone, so the field will be empty until a value is entered and saved again

I think the empty string as a signal for deletion seems safe since I'm using a generic component so the inputs are explicitly controlled in that sense and we know we always get safe values, e.g. only one of a valid number or an empty string. The only thing I don't totally love is having to update the `Limit` interface to accommodate this empty string value, e.g. `quantity: number | string;` 👈 ideally this would just be `number` only. But, I like the idea of managing an extra piece of state (limits to be deleted) less so what I've implemented here is actually the most ideal considering. 

I believe @xquanluu should be able to implement something similar on the PR for the main branch.

**Comment by xquanluu** [comment]
Added delete Limits to PR for main branch
