### ISSUE TITLE
Feature: User scope

### ISSUE THREAD

**Issue by kitajchuk** [jambonz/jambonz-webapp#153]
Maybe I can articulate generally what I'm thinking about here (high-level) so we’re all on the same page regarding user scope implementation on the FE.

We already did the first part which was to implement the JWT and parse user data from that!

Which brings me to the next piece: scope. I created a basic ACL concept which supported the singleton Admin concept and is currently only practically used for the MS Teams Tenants view:
https://github.com/jambonz/jambonz-webapp/blob/main/src/containers/internal/navi/index.tsx#L169-L188
https://github.com/jambonz/jambonz-webapp/blob/main/src/containers/internal/navi/items.ts#L68-L72
https://github.com/jambonz/jambonz-webapp/blob/main/src/containers/internal/views/ms-teams-tenants/index.tsx#L218-L221

I think this can stay in place for MS Teams Tenants as is but the singleton Admin will just be removed. As for user scope we can make that its own concept by providing a condition for each of the 3 user scopes. From there we can continue to use the ACL architecture as designed and manage user access to things based on their scope. We have a simple component for this as well:
https://github.com/jambonz/jambonz-webapp/blob/main/src/components/access-control.tsx

I was thinking we could maybe change things up a bit for user scope and implement an enum (stubbed one in already I think—commented out)  such that permissions cascade. E.g. A user can only see limited things, A service provider can see whatever a user can see plus their scope and an admin can see everything. The enum allows you to scope things with simple logic: (currentUser.scope >= someScope). Very nice.

Well, that's the gist of it. I'm sure there will be more to consider but I think this general approach is the right way to begin thinking about the implementation such that it fits well into the app architecture on the frontend and can scale well for the needs.

If we need to restrict making some API calls we can discuss that as well but I’d imagine getting the UI properly restricted by user scope would achieve that, at least mostly.

**Comment by kitajchuk** [comment]
@EgleHelms @davehorton This is the high level of my thinking in general user permissions 👍

**Comment by EgleHelms** [comment]
@kitajchuk currently the "permissions" do not play a role at all.
We are limiting and building everything according to the 3 scopes for users - admin/SP/account. And for that, we haven't implemented the enum approach. Let me know if we should use this for the scope too.
Also, I think that the ACL component works well with the parseJwt concept. We can condition different scopes and create props like "renderNoAccess" to render different things for different users (@davehorton mentioned he wants some different views in some cases - e.g. instead of an Account list, an account user would see "Account" in the nav and it would lead to the Account edit page.).

FYI, we are also a bit under time pressure here. So if you have some very specific ideas, maybe it would be wise to apply the adjustments asap and make an example usage so I can start applying it across the app.

Regarding the API, I actually started adjusting some of the things on the backend that were not allowed. Like when calling /ServiceProviders as non-admin, you will now get current provider data if your scope is non-admin, and /PasswordSettings are allowed to all. I assume long term we will also restrict other things like recent calls, etc... to the scope - response contains already filtered results. But for now, the FE will do.

**Comment by kitajchuk** [comment]
@EgleHelms @davehorton looks like I’m not going to have time to do the setup so I’ll outline what I was thinking a bit more concretely here and @EgleHelms will be able to run with it.

Okay so first we’d want a UserScopes enum. I originally stubbed a comment in as permissions but you can just switch the enum concept to be for scope:

https://github.com/jambonz/jambonz-webapp/blob/b1a4c0403190087f8c9bba14749263049327a345/src/api/types.ts#L22

Okay so when we parse the token and set the user data in the store we’ll want to now add the users scope as the enum value as well, so it would be 0-2 which maps to our string values. We can leave our UserScope union type as is since the rest of the code uses that because our api doesn’t use numeric scopes.

For now we can leave the AccessControl component and utils alone because it would just be more work to muck with it. I’ll make a backlog issue to clean that up when we have time later.

For this we can make a new ScopedAccess component that receives a scope prop that is typed to the UserScope enum. This component would select the current user from the store and do a simple >= comparison operator between the users enum scope and the scope prop to determine if it should render the children.

We may need to do things outside of react JSX so we night also create a utility function that does a similar thing logically. Possibly a hook would be of service as well. With the hook you could use it in the new component too, probably, and consolidate your logic while providing versatility.

For this new component let’s include a cypress test too. 

Okay I think that should get you going I hope. Ping me with questions 🤘
