### ISSUE TITLE
bug: can't provide custom voice name when using Azure custom voice

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-webapp#307]
to recreate: add a Microsoft speech credential using a custom voice name.  You can create the speech credential, but when you set it as the default for an application you are given the standard list of Azure voices, whereas you would need to specify the name you gave the custom voice.

What should happen: in the Applications view if you select for TTS an Azure speech credential which is using a custom voice, instead of the dropdown list of voices it should be an input field instead where you can just type in the name

**Comment by xquanluu** [comment]
Start working on this

**Comment by xquanluu** [comment]
Closing issue as Jambonz is already working like that.

**Comment by Catharsis68** [comment]
@xquanluu 

I think this issue is not working in the recent jambonz version:

When creating a speech provider type Microsoft with **Use for custom voice: true** 
On application level when selecting Microsoft as TTS  - there should be an input field to define the voice instead of the pre-built voice list.

![Screenshot from 2023-08-24 15-02-13](https://github.com/jambonz/jambonz-webapp/assets/6165055/be288148-e346-4886-a46e-c7ec6e6d5072)
![Screenshot from 2023-08-24 15-01-48](https://github.com/jambonz/jambonz-webapp/assets/6165055/d3a1d259-627a-4edb-9ab1-9dea25043046)

**Comment by davehorton** [comment]
@xquanluu can you take another look at this

**Comment by xquanluu** [comment]
Deployed to jambonzone
