### ISSUE TITLE
"invalid count value" for refresh's Speech Service view

### ISSUE THREAD

**Issue by khanghugo** [jambonz/jambonz-webapp#88]
@kitajchuk 

I just boot this up and tested a bit and this is not working well. I tried both typing and copy-pasting into the input field and it do be like that. 

The SQL looks fine. 

I can have some time with it later as soon as I finish some basic features for Carrier view.

The REST API is running on the other PR, not the main branch. Let see if that is the problem.

**Comment by khanghugo** [comment]
I run on the main branch and only aws works while it reports other vendors are not on the list.

**Comment by kitajchuk** [comment]
> @kitajchuk
> 
> I just boot this up and tested a bit and this is not working well. I tried both typing and copy-pasting into the input field and it do be like that.
> 
> The SQL looks fine.
> 
> I can have some time with it later as soon as I finish some basic features for Carrier view.
> 
> The REST API is running on the other PR, not the main branch. Let see if that is the problem.

I tested all vendors and it works fine. Do you have a real Google service key? @davehorton gave me one to test with. I also used real AWS credentials but I don’t have Microsoft or wellsaid credentials to test with. Maybe more clarity documenting what isn’t working would be helpful here?

**Comment by khanghugo** [comment]
I was testing with microsoft and wellsaid randomly typed api key. I did not tick mark any use so it doesn't test for anything. I will circle it back later and see what is wrong on my end.

**Comment by kitajchuk** [comment]
> I was testing with microsoft and wellsaid randomly typed api key. I did not tick mark any use so it doesn't test for anything. I will circle it back later and see what is wrong on my end.

Cool I’ll test again. Is the error a client side error or an api response error?

**Comment by kitajchuk** [comment]
@khanghugo I recreated this issue by entering an api key that was two characters long. So, the bug is in the new obscuring code on the backend for the PR you have open. It's trying to perform string manipulation on too short of a string. This is similar to the bug I had on the client side runtime which I fixed by simply returning the original string from the obscuring function if its length was less than or equal too the unobscured value which is `6`. I think we need to handle this so there's no errors. We should include safety for this on the backend code for that PR but we can also have a min-length on the api key fields on the frontend to also help avoid the scenario altogether. This is definitely an edge case since this feature is not designed for typing in random characters. Real users will be using real api keys / credentials and most likely copy pasting since no one types api keys out by hand 🤔. Regardless, the edge case fixes are necessary so I can make those fixes while you keep working on the carrier views.

**Comment by kitajchuk** [comment]
@khanghugo I'm closing this issue with the note that the error is fixed in our backend PR for obscuring the credentials which is where the bug was. Commit here so pull latest on this backend branch 👍 

Commit: https://github.com/jambonz/jambonz-api-server/pull/59/commits/fc10aac31ac2e788cd9155bc5a5a39680873b7f4
